project 'LemonMix.xcodeproj'

platform :ios, '9.0'

target 'LemonMix' do
pod 'LemonKit','1.0.12'
end

target 'LemonMixSamples' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LemonMixSamples

end
